version: 2

jobs:
  macos:
    macos:
      xcode: "9.2"
    steps:
      - checkout
      - run: swift build
      - run: swift test
  linux:
    docker:
      - image: swift:4.2
    steps:
      - checkout
      - run: 
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test
  linux-41:
    docker:
      - image: codevapor/swift:4.1
    steps:
      - checkout
      - run: 
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test
  linux-release:
    docker:
      - image: swift:4.2
    steps:
      - checkout
      - run: 
          name: Compile code with optimizations
          command: swift build -c release
  compat-suite:
    docker:
      - image: swift:4.2
    steps:
      - run: echo ""
  linux-compat-api-template:
    docker:
      - image: swift:4.2
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: ""
    steps:
      - run:
          name: Clone API Template
          command: git clone -b beta https://github.com/vapor/api-template.git
          working_directory: ~/
      - run:
          name: Unpin dependencies
          command: rm Package.resolved
          working_directory: ~/api-template
      - run:
          name: Switch API Template to this Vapor revision
          command: swift package edit Vapor --revision $CIRCLE_SHA1
          working_directory: ~/api-template
      - run:
          name: Run API Template unit tests
          command: swift test
          working_directory: ~/api-template
  linux-compat-swift-commerce-order-system:
    docker:
      - image: swift:4.2
    steps:
      - run:
          name: Maintainers
          command: echo "@calebkleveter, @proggeramlug contact via discord"
      - run:
          command: git clone -b 0.1.0 https://github.com/SwiftCommerce/OrderSystem
          working_directory: ~/
      - run:
          command: rm Package.resolved
          working_directory: ~/OrderSystem
      - run:
          command: swift package edit Vapor --revision $CIRCLE_SHA1
          working_directory: ~/OrderSystem
      - run:
          command: swift test
          working_directory: ~/OrderSystem
  linux-compat-swift-commerce-product-manager:
    docker:
      - image: swift:4.2
    steps:
      - run:
          name: Maintainers
          command: echo "@calebkleveter, @proggeramlug contact via discord"
      - run:
          command: git clone -b 0.1.0 https://github.com/SwiftCommerce/ProductManager
          working_directory: ~/
      - run:
          command: rm Package.resolved
          working_directory: ~/ProductManager
      - run:
          command: swift package edit Vapor --revision $CIRCLE_SHA1
          working_directory: ~/ProductManager
      - run:
          command: swift test
          working_directory: ~/ProductManager
  linux-compat-skelpo-user-manager:
    docker:
      - image: swift:4.2
    steps:
      - run:
          name: Maintainers
          command: echo "@calebkleveter, @proggeramlug contact via discord"
      - run:
          command: git clone -b 0.1.8 https://github.com/skelpo/UserManager
          working_directory: ~/
      - run:
          command: swift package edit Vapor --revision $CIRCLE_SHA1
          working_directory: ~/UserManager
      - run:
          command: swift test
          working_directory: ~/UserManager
  linux-compat-ether-cli-ether:
    docker:
      - image: swift:4.2
    steps:
      - run:
          name: Maintainer
          command: echo "@calebkleveter contact via discord"
      - run:
          command: git clone -b 2018.10.03 https://github.com/Ether-CLI/Ether
          working_directory: ~/
      - run:
          command: rm Package.resolved
          working_directory: ~/Ether
      - run:
          command: swift package edit Vapor --revision $CIRCLE_SHA1
          working_directory: ~/Ether
      - run:
          command: swift build
          working_directory: ~/Ether
  linux-compat-asensei-auth-jwt:
    docker:
      - image: swift:4.2
    steps:
      - run:
          name: Maintainer
          command: echo "@valeriomazzeo, @dlbuckley Vapor Discord DM, email"
      - run:
          command: git clone -b 1.0.0 https://github.com/asensei/vapor-auth-jwt
          working_directory: ~/
      - run:
          command: swift package edit Vapor --revision $CIRCLE_SHA1
          working_directory: ~/vapor-auth-jwt
      - run:
          command: swift build
          working_directory: ~/vapor-auth-jwt
  linux-compat-liveui-apicore:
    docker:
      - image: swift:4.2
      - image: circleci/postgres:9.6.5-alpine-ram
    steps:
      - run:
          name: Maintainer
          command: echo "@rafiki270, Vapor Discord, Twitter, Email"
      - run:
          command: git clone https://github.com/LiveUI/ApiCore
          working_directory: ~/
      - run:
          command: git checkout fd45ad30d0e6691be31ede4e6524853328fa49f4
          working_directory: ~/ApiCore
      - run:
          command: apt-get -qq update && apt-get install -y libgd-dev
          working_directory: ~/ApiCore
      - run:
          command: swift package edit Vapor --revision $CIRCLE_SHA1
          working_directory: ~/ApiCore
      - run:
          command: swift build
          working_directory: ~/ApiCore
      - run:
          command: swift test
          working_directory: ~/ApiCore
  linux-compat-liveui-s3:
    docker:
      - image: swift:4.2
    steps:
      - run:
          name: Maintainer
          command: echo "@rafiki270, Vapor Discord, Twitter, Email"
      - run:
          command: git clone https://github.com/LiveUI/S3
          working_directory: ~/
      - run:
          command: git checkout 1f911e5148f53966045d3953f45fa989c4e1ee05
          working_directory: ~/S3
      - run:
          command: swift package edit Vapor --revision $CIRCLE_SHA1
          working_directory: ~/S3
      - run:
          command: swift build
          working_directory: ~/S3
      - run:
          command: swift test
          working_directory: ~/S3
workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-41
      - linux-release:
          requires:
            - linux
      - compat-suite:
          type: approval
      - linux-compat-api-template:
          requires:
            - compat-suite
      - linux-compat-swift-commerce-order-system:
          requires:
            - compat-suite
      - linux-compat-swift-commerce-product-manager:
          requires:
            - compat-suite
      - linux-compat-skelpo-user-manager:
          requires:
            - compat-suite
      - linux-compat-ether-cli-ether:
          requires:
            - compat-suite
      - linux-compat-asensei-auth-jwt:
          requires:
            - compat-suite
      - linux-compat-liveui-apicore:
          requires:
            - compat-suite
      - linux-compat-liveui-s3:
          requires:
            - compat-suite
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master   
    jobs:
      - linux
