version: 2

jobs:
  macos:
    macos:
      xcode: "9.2"
    steps:
      - checkout
      - run: swift build
      - run: swift test

  linux:
    docker:
      - image: norionomura/swift:swift-4.1-branch
    steps:
      - checkout
      - run:
          name: Update APT
          command: apt-get update
      - run:
          name: Install Swift NIO dependencies
          command: apt-get install -yq pkg-config libssl-dev
      - run: 
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test
      - run: 
          name: Compile code with optimizations
          command: swift build -c release

workflows:
  version: 2
  commit:
    jobs:
      - linux
      # - macos
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
          branches:
            only:
              - master
              - nio
    jobs:
      - linux
      # - macos
      