import SwiftSyntax
import SwiftSyntaxMacros
import SwiftSyntaxBuilder
import Foundation

public struct ControllerMacro: ExtensionMacro, MemberAttributeMacro, MemberMacro {
    public static func expansion(of node: AttributeSyntax, attachedTo declaration: some DeclGroupSyntax, providingAttributesFor member: some DeclSyntaxProtocol, in context: some MacroExpansionContext) throws -> [AttributeSyntax] {
        []
    }

    public static func expansion(of node: AttributeSyntax, providingMembersOf declaration: some DeclGroupSyntax, conformingTo protocols: [TypeSyntax], in context: some MacroExpansionContext) throws -> [DeclSyntax] {
        []
    }

    public static func expansion(of node: AttributeSyntax, attachedTo declaration: some DeclGroupSyntax, providingExtensionsOf type: some TypeSyntaxProtocol, conformingTo protocols: [TypeSyntax], in context: some MacroExpansionContext) throws -> [ExtensionDeclSyntax] {
        // Parse the @Controller(...) path prefix. Supports string literals and `Type.self` for dynamic params.
        let controllerArgs: LabeledExprListSyntax? = switch node.arguments {
        case .argumentList(let args): args
        default: nil
        }
        let prefix = HTTPMethodMacroUtilities.parsePathComponents(from: controllerArgs, startingIndex: 0)

        // Find all functions with route macros
        let functions = try declaration.memberBlock.members.compactMap { member -> (FunctionDeclSyntax, String, [String], [String])? in
            guard let funcDecl = member.decl.as(FunctionDeclSyntax.self) else {
                return nil
            }

            // Look for HTTP method attributes
            for attribute in funcDecl.attributes {
                guard case let .attribute(attr) = attribute,
                      let identifier = attr.attributeName.as(IdentifierTypeSyntax.self),
                      ["GET", "POST", "PUT", "DELETE", "PATCH", "HTTP"].contains(identifier.name.text) else {
                    continue
                }

                let arguments: LabeledExprListSyntax? = switch attr.arguments {
                case .argumentList(let arguments): arguments
                default: nil
                }
                let httpMethod: String
                let customHTTPMethod: Bool
                if identifier.name.text == "HTTP" {
                    // Take the first argument as the HTTP method
                    guard let argument = arguments?.first else {
                        throw MacroError.missingArguments("Controller")
                    }
                    httpMethod = argument.expression.description.replacingOccurrences(of: ".", with: "")
                    customHTTPMethod = true
                } else {
                    httpMethod = identifier.name.text
                    customHTTPMethod = false
                }

                // Parse the route-local path components, indexed continuously after the prefix.
                let route = HTTPMethodMacroUtilities.parsePathComponents(
                    from: arguments,
                    startingIndex: prefix.nextIndex,
                    skipFirstUnlabeled: customHTTPMethod
                )

                // Check for @AuthMiddleware
                let middlewareExprs: [String] = {
                    guard let authInfo = HTTPMethodMacroUtilities.parseAuthMiddleware(from: funcDecl) else {
                        return []
                    }
                    return authInfo.middlewares
                }()

                return (funcDecl, httpMethod, route.routeRegistrationSegments, middlewareExprs)
            }

            return nil
        }

        // Generate the RouteCollection boot function
        var registrationBody = ""

        // Choose the builder expression each route hangs off of.
        // When @Controller has a non-empty path prefix, introduce `let group = routes.grouped(...)`
        // so nested groups (for middleware, later) can chain cleanly.
        let baseBuilder: String
        if prefix.routeRegistrationSegments.isEmpty {
            baseBuilder = "routes"
        } else {
            let prefixLiteral = prefix.routeRegistrationSegments.joined(separator: "\", \"")
            registrationBody += """
            let group = routes.grouped("\(prefixLiteral)")

            """
            baseBuilder = "group"
        }

        for (functionDeclaration, method, pathComponents, middlewares) in functions {
            let path = pathComponents.joined(separator: "\", \"")
            let methodLower = method.lowercased()

            // Call the function generated by the HTTP Method Macros
            let functionName = "_route_\(functionDeclaration.name.text)"
            let pathRegistration = if path == "" {
                ""
            } else {
                "(\"\(path)\")"
            }

            if middlewares.isEmpty {
                registrationBody += """
                \(baseBuilder).\(methodLower)\(pathRegistration) { req async throws -> Response in
                    try await self.\(functionName)(req: req)
                }

                """
            } else {
                let middlewareList = middlewares.joined(separator: ", ")
                registrationBody += """
                \(baseBuilder).grouped(\(middlewareList)).\(methodLower)\(pathRegistration) { req async throws -> Response in
                    try await self.\(functionName)(req: req)
                }

                """
            }
        }

        let registrationFunc: DeclSyntax = """
        func boot(routes: any RoutesBuilder) throws {
        \(raw: registrationBody)
        }
        """

        let extensionSyntax: DeclSyntax = """
        extension \(type.trimmed): RouteCollection {
            \(registrationFunc)
        }
        """

        guard let extensionDecl = extensionSyntax.as(ExtensionDeclSyntax.self) else {
            return []
        }

        return [extensionDecl]
    }
}
