import SwiftSyntax
import SwiftSyntaxMacros
import SwiftSyntaxBuilder
import Foundation

public struct ControllerMacro: ExtensionMacro, MemberAttributeMacro, MemberMacro {
    public static func expansion(of node: AttributeSyntax, attachedTo declaration: some DeclGroupSyntax, providingAttributesFor member: some DeclSyntaxProtocol, in context: some MacroExpansionContext) throws -> [AttributeSyntax] {
        []
    }

    public static func expansion(of node: AttributeSyntax, providingMembersOf declaration: some DeclGroupSyntax, conformingTo protocols: [TypeSyntax], in context: some MacroExpansionContext) throws -> [DeclSyntax] {
        []
    }

    public static func expansion(of node: AttributeSyntax, attachedTo declaration: some DeclGroupSyntax, providingExtensionsOf type: some TypeSyntaxProtocol, conformingTo protocols: [TypeSyntax], in context: some MacroExpansionContext) throws -> [ExtensionDeclSyntax] {
        let topLevelItems: [Syntax] = declaration.memberBlock.members.map { Syntax($0.decl) }
        let candidateFunctions = collectRouteCandidates(items: topLevelItems, outerMiddlewares: [])

        // Find all functions with route macros
        let functions = try candidateFunctions.compactMap { (funcDecl, outerMiddlewares) -> (FunctionDeclSyntax, String, [String], [String])? in

            // Look for HTTP method attributes
            for attribute in funcDecl.attributes {
                guard case let .attribute(attr) = attribute,
                      let identifier = attr.attributeName.as(IdentifierTypeSyntax.self),
                      ["GET", "POST", "PUT", "DELETE", "PATCH", "HTTP"].contains(identifier.name.text) else {
                    continue
                }

                let arguments: LabeledExprListSyntax? = switch attr.arguments {
                case .argumentList(let arguments): arguments
                default: nil
                }
                let httpMethod: String
                let customHTTPMethod: Bool
                if identifier.name.text == "HTTP" {
                    // Take the first argument as the HTTP method
                    guard let argument = arguments?.first else {
                        throw MacroError.missingArguments("Controller")
                    }
                    httpMethod = argument.expression.description.replacingOccurrences(of: ".", with: "")
                    customHTTPMethod = true
                } else {
                    httpMethod = identifier.name.text
                    customHTTPMethod = false
                }

                // Parse path components
                var pathComponents: [String] = []
                var currentDynamicPathParameterIndex = 0
                if let arguments {
                    for (index, arg) in arguments.enumerated() {
                        // If we're a custom HTTP method, discard the first one
                        if customHTTPMethod && index == 0 {
                            continue
                        }
                        let exprStr = arg.expression.description.trimmingCharacters(in: .whitespacesAndNewlines)

                        // Check if it's a type (contains .self)
                        if exprStr.hasSuffix(".self") {
                            let typeName = exprStr.replacingOccurrences(of: ".self", with: "")
                            pathComponents.append(":\(typeName.lowercased())\(currentDynamicPathParameterIndex)")
                            currentDynamicPathParameterIndex += 1
                        } else {
                            // It's a string literal
                            let cleaned = exprStr.trimmingCharacters(in: CharacterSet(charactersIn: "\""))
                            pathComponents.append(cleaned)
                        }
                    }
                }

                var combinedMiddlewares = outerMiddlewares
                if let authInfo = HTTPMethodMacroUtilities.parseAuthMiddleware(from: funcDecl) {
                    combinedMiddlewares.append(contentsOf: authInfo.middlewares)
                }

                return (funcDecl, httpMethod, pathComponents, combinedMiddlewares)
            }

            return nil
        }

        // Generate the RouteCollection boot function
        var registrationBody = ""

        for (functionDeclaration, method, pathComponents, middlewares) in functions {
            let path = pathComponents.joined(separator: "\", \"")
            let methodLower = method.lowercased()

            // Call the function generated by the HTTP Method Macros
            let functionName = "_route_\(functionDeclaration.name.text)"
            let pathRegistration = if path == "" {
                ""
            } else {
                "(\"\(path)\")"
            }

            if middlewares.isEmpty {
                registrationBody += """
                routes.\(methodLower)\(pathRegistration) { req async throws -> Response in
                    try await self.\(functionName)(req: req)
                }

                """
            } else {
                let middlewareList = middlewares.joined(separator: ", ")
                registrationBody += """
                routes.grouped(\(middlewareList)).\(methodLower)\(pathRegistration) { req async throws -> Response in
                    try await self.\(functionName)(req: req)
                }

                """
            }
        }

        let registrationFunc: DeclSyntax = """
        func boot(routes: any RoutesBuilder) throws {
        \(raw: registrationBody)
        }
        """

        let extensionSyntax: DeclSyntax = """
        extension \(type.trimmed): RouteCollection {
            \(registrationFunc)
        }
        """

        guard let extensionDecl = extensionSyntax.as(ExtensionDeclSyntax.self) else {
            return []
        }

        return [extensionDecl]
    }

    /// Recursively walks struct members / closure statements, collecting function
    /// declarations together with any middlewares inherited from enclosing
    /// `#Middleware(...)` or `#AuthMiddleware(...)` groupings
    private static func collectRouteCandidates(
        items: [Syntax],
        outerMiddlewares: [String]
    ) -> [(FunctionDeclSyntax, [String])] {
        var results: [(FunctionDeclSyntax, [String])] = []

        for item in items {
            if let funcDecl = item.as(FunctionDeclSyntax.self) {
                results.append((funcDecl, outerMiddlewares))
                continue
            }

            guard let macroCall = GroupingMacroHelpers.macroCall(item),
                  let trailing = macroCall.trailingClosure
            else {
                continue
            }

            let innerItems = trailing.statements.map { Syntax($0.item) }

            switch macroCall.macroName {
            case "Middleware":
                let middlewareList = macroCall.arguments.map {
                    $0.expression.description.trimmingCharacters(in: .whitespacesAndNewlines)
                }
                results.append(contentsOf: collectRouteCandidates(
                    items: innerItems,
                    outerMiddlewares: outerMiddlewares + middlewareList
                ))

            case "AuthMiddleware":
                let authAttrArgs = macroCall.arguments.map {
                    $0.expression.description.trimmingCharacters(in: .whitespacesAndNewlines)
                }.joined(separator: ", ")
                let authAttr = AttributeSyntax(stringLiteral: "@AuthMiddleware(\(authAttrArgs))")

                let innerCandidates = collectRouteCandidates(
                    items: innerItems,
                    outerMiddlewares: outerMiddlewares
                )
                for (innerFunc, inheritedMiddlewares) in innerCandidates {
                    var newAttrs = AttributeListSyntax()
                    newAttrs.append(.attribute(authAttr))
                    for a in innerFunc.attributes { newAttrs.append(a) }
                    results.append((innerFunc.with(\.attributes, newAttrs), inheritedMiddlewares))
                }

            default:
                continue
            }
        }

        return results
    }
}
